### PR TITLE
screenR.vim compatible with Vim-R-plugin version 1.2.5

### PR DESCRIPTION
**Pull request by ssayols**
Hi Jakson,
I don't know if you still maintain this script. I added some code from your original StartR() and StartR_TmuxSplit() function to make it comptaible with Vim-R-plugin 1.2.5

Just tested some stuff: send lines to the console, called help, complete object names, complete arguments, call object browser, and knit an Rmd document. So far these things, work ;)

cheers,
Sergi

### CODE REVIEW

**Comment by jalvesaq** [comment]
Thanks for the pull request! Would you like to maintain this script? If yes, instead of forking it, you could create you own repository with the same name (or other name, if you prefer), and I would put in my screenR.vim:

```vim
call RWarningMsgInp("The screenR.vim has new maintainer and new address. See: github.com/ssayols/screenR")
finish
```

I would also update the screenR.vim address in the Vim-R-plugin documentation.

**Comment by ssayols** [comment]
sure, I'll be happy to help! I created a fresh new screenR repo, feel free to put any stuff there.

I'm stuck to GNUscreen in our cluster, so long life to the screenR.vim!

**Comment by jalvesaq** [comment]
Great! Please, upload your modified script! The screenR.vim is yours now. I no longer use screen, and I stopped a long time ago testing whether this script was still compatible with the rest of the Vim-R-plugin. I already updated the Vim-R-plugin documentation: https://github.com/jcfaria/Vim-R-plugin/commit/2ec00943df2aaf1dc8e7c480e9d7fb2483c74151

**Comment by jalvesaq** [comment]
I am going to merge your pull request to register your contribution and, then, I will disable the script.

**Comment by ssayols** [comment]
thanks! I'll try to keep it up-to-date with the Vim-R-plugin wihtout bothering you. I guess GNUscreen is still preferred to tmux in some cluster installations. How were the download stats of the screenR plugin? and how about compared to the Vim-R-plugin?
cheers,
Sergi

**Comment by jalvesaq** [comment]
I know that GNUscreen is the only option in some cases, but I can't maintain both screen and tmux. Where can I see the download statistics?

**Comment by ssayols** [comment]
I use to have the repos in sourceforge... After googling a little bit seems it's not possible to get the download metrics in github. No worries ;)

**Pull request merged**
